#!/usr/bin/env node
"use strict";

const { Core } = require("../../../../index");
const TraceMocksPlugin = require("./TraceMocksPlugin");

const handleError = error => {
  console.error(`Error: ${error.message}`);
  process.exitCode = 1;
};

const start = () => {
  try {
    const mocksServer = new Core({
      plugins: [TraceMocksPlugin],
      configFile: "add-plugins.config.js"
    });

    return mocksServer.start().catch(handleError);
  } catch (error) {
    return handleError(error);
  }
};

start();
